class AccountInfoPage <SitePrism::Page
  set_url 'https://member.whoami-integration.integration.teladoc.io/registrations/account_info'

  element :resident_address_line1_field, '#resident_address_line1'
  element :resident_address_line2_field, '#resident_address_line2'
  element :resident_city_field, '#resident_city'
  element :resident_state_field, '#resident_state'
  element :primary_phone_number_field, '#primaryPhoneNumber-spnf-spnf-phone-number'
  element :username_field, '#username'
  element :password_field, '#password'
  element :password_confirmation_field, '#password_confirmation'
  element :security_question_id_1_dropdown, '#security_question_id_1'
  element :security_question_response_1_field, '#security_question_response_1'
  element :security_question_id_2_dropdown, '#security_question_id_2'
  element :security_question_response_2_field, '#security_question_response_2'
  element :security_question_id_3_dropdown, '#security_question_id_3'
  element :security_question_response_3_field, '#security_question_response_3'
  element :billing_card_type_dropdown, '#billing_card_type'
  element :billing_card_number_field, '#billing_card_number'
  element :billing_expiration_month_dropdown, '#billing_expiration_month'
  element :billing_expiration_year_dropdown, '#billing_expiration_year'
  element :billing_address_line1_field, '#billing_address_line1'
  element :billing_address_city_field, '#billing_address_city'
  element :billing_address_state_field, '#billing_address_state'
  element :billing_address_postal_field, '#billing_address_postal'
  element :submit_button, '#submit'
end